export const FETCH_CODERS_REQUEST = 'FETCH_CODERS_REQUEST'
export const FETCH_CODERS_SUCCESS = 'FETCH_CODERS_SUCCESS'
export const FETCH_CODERS_FAILURE = 'FETCH_CODERS_FAILURE'

export const FETCH_CODER_FEEDBACK_REQUEST = 'FETCH_CODER_FEEDBACK_REQUEST'
export const FETCH_CODER_FEEDBACK_SUCCESS = 'FETCH_CODER_FEEDBACK_SUCCESS'
export const FETCH_CODER_FEEDBACK_FAILURE = 'FETCH_CODER_FEEDBACK_FAILURE'

export const FETCH_CODER_REQUEST = 'FETCH_CODER_REQUEST'
export const FETCH_CODER_SUCCESS = 'FETCH_CODER_SUCCESS'
export const FETCH_CODER_FAILURE = 'FETCH_CODER_FAILURE'

export const ADD_FEEDBACK = 'ADD_FEEDBACK'

export const TOGGLE_CODER_STATUS = 'TOGGLE_CODER_STATUS'

export const FETCH_ALL_FEEDBACKS_REQUEST = 'FETCH_ALL_FEEDBACKS_REQUEST'
export const FETCH_ALL_FEEDBACKS_SUCCESS = 'FETCH_ALL_FEEDBACKS_SUCCESS'
export const FETCH_ALL_FEEDBACKS_FAILURE = 'FETCH_ALL_FEEDBACKS_FAILURE'
